### ISSUE TITLE
Footswitch doesn't seem to work with OS X. 

### ISSUE THREAD

**Issue by mitchell-johnson** [alevchuk/vim-clutch#15]
## The footswitch software that is linked in the readme doesn't seem to work with os x.

I have found a work-around using a single foot pedal and the keyboard [Keyboard Maestro](http://www.keyboardmaestro.com/main/) software. 
1. Connect the pedal to a windows machine and install the bundled software. 
2. Configure the pedal to perform a (ctrl) button press and apply to device.
   1. Make sure the the long press option is selected so that holding down the pedel simulates holding down the key.
3. Connect the pedal to the OS X machine.
4. Go to System Preferences -> Keyboard -> Modifier Keys 
   1. Select FootswitchV1.1 from the drop-down list at the top.
   2. In the Control key field set it to No Action.
   3. Exit system preferences 
5. Open up the Keyboard Maestro macro editor
   1. Create a new macro.
   2. In the trigger field choose Device Trigger
   3. The device field should be selected and now press down the pedal once. The field should now say something like: FootSwitchV1.1 Left Control 
   4. From this point you can set macros to execute when the pedal is pressed, released or Down.
   5. Configure any actions you want your pedal to do... 

Thanks an I hope I have helped someone.
Mitchell 
elwesties(at)gmail.com

**Comment by alevchuk** [comment]
Pedal programming had to be done via windows. That was the hardest part for me - find a windows computer.

That's why rgerganov wrote the driver for programing the device via Linux:
https://github.com/rgerganov/footswitch

You probably know this, however lets be clear: once the pedal is programmed it will work on any Mac, Linux, and Windows.

**Comment by mitchell-johnson** [comment]
Thanks for the reply! Yes my mistake you could also use a linux box to do the footpedal configuration. I just wanted to point out that rgerganov's footswitch software doesn't work on os x easily at this stage. 

Secondly I also wanted to point out that you dont need to purchase two footswitches and hack them together to get it to function well on os x. Using keyboard maestro is actually very useful as you can program for pressed and released with one pedal.

Thanks again
Mitchell

**Comment by alevchuk** [comment]
Nice! Thanks!

**Comment by mateomtb** [comment]
Thank your for this tip on os X and using 1 pedal. Just wanted to point out too that although the pedal works (input recognized) I couldn't get the pedal to be recognized by my vmware windows machine to use the supplied GUI pedal tool. Also the CLI for my Linux machine that is also on vmware wouldn't recognize the pedal and as documented it does not work as is in OS X.

https://github.com/rgerganov/footswitch/issues/1

Getting to a physical windows machine was also a pain for me, finally got to one on a coworkers desk.

The pedal idea is awesome! We are going to hold a VIM Olympics at work and I'm going to use the pedal to rock the "Open Class" category.
