### ISSUE TITLE
isn't vim nnoremap solves problem of second pedal?

### ISSUE THREAD

**Issue by sandric** [alevchuk/vim-clutch#17]
I also have two pedals for typing, along with my homemade arduino-based keyboard remapper, but I'm using right pedal for shift, and left for esc, but to be able to switch to insert mode back if I jumped to normal before using pedal, you can just write in your .vimrc 

`noremap <Esc> i`

Works great for me)

**Comment by alevchuk** [comment]
Vim-clutch is designed to work without any changes to the Vim configuration. And with just one pedal.

It just sends `<Esc> i` on pedal down, and `<Esc>` when you release it.

The idea is that one has to hold the pedal down while typing, but to get back to normal more (e.g. for navigating) one just releases the pedal.

**Comment by sandric** [comment]
oh. now I get it, thx). Actually I think I'll even try it now.
